# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Backend Build and deploy

on:
    workflow_run:
        workflows: ["Backend Tester"]
        types: [completed]
        branches:
            - master

concurrency:
    group: backend-tester-${{ github.event.workflow_run.head_sha }}
    cancel-in-progress: true

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: apps/backend

    steps:
      - uses: actions/checkout@v4
        with:
            ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'apps/backend/composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Create SQLite database file
        run: touch database/database.sqlite
        
      - name: Publish Wayfinder
        run: php artisan wayfinder:generate
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check if package.json exists
        id: check_package_json
        uses: andstor/file-existence-action@v1
        with:
          files: 'apps/backend/package.json'

      - name: Run npm install if package.json exists
        if: steps.check_package_json.outputs.files_exists == 'true'
        run: npm ci

      - name: Run npm build if package.json exists
        if: steps.check_package_json.outputs.files_exists == 'true'
        run: npm run build

      - name: Make startup script executable
        run: chmod +x startup.sh

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: apps/backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DD75B817A0A64D69A81226352FBAA5C6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_19E926FB270A4504A4C11FAC738FDC94 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4E33C29952DD42CB96A3C949003B9C76 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'ballisticserver'
          slot-name: 'Production'
          package: .
          